version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eod-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/eod
      - SPRING_DATASOURCE_USERNAME=eod_user
      - SPRING_DATASOURCE_PASSWORD=eod_password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - eod-network

  mysql:
    image: mysql:8.0
    container_name: eod-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eod
      MYSQL_USER: eod_user
      MYSQL_PASSWORD: eod_password
    ports:
      - "3306:3306"
    networks:
      - eod-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


networks:
  eod-network:
    driver: bridge